import "./globals.scss";
import styles from "./page.module.scss";
import { Victor_Mono } from "next/font/google";
import localFont from "next/font/local";
import type { Metadata } from "next";
import { Language } from "@/lib/types";
import Footer from "@/components/Footer/footer";

const victorMono = Victor_Mono();

const cooperHewittBook = localFont({
    src: "../../public/fonts/CooperHewitt-Book.otf"
});

const cooperHewittBoldItalic = localFont({
    src: "../../public/fonts/CooperHewitt-BoldItalic.otf"
});

const cooperHewittSemibold = localFont({
    src: "../../public/fonts/CooperHewitt-Semibold.otf"
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const Home = async ({ children, params }: { children: React.ReactNode, params: Promise<{ language: Language }> }) => {
    const { language } = await params;

    return (
        <html lang={language}>
            <body className={styles.body}>
                <div id="scroll-container">
                    {children}
                    <Footer language={language} />
                </div>
            </body>
        </html>
    )
}

export default Home;