import "./globals.scss";
import styles from "./page.module.scss";
import { Victor_Mono } from "next/font/google";
import localFont from "next/font/local";
import { home } from "@/lib/home";
import Hero from "@/components/Hero/hero";
import type { Metadata } from "next";
import { Language } from "@/lib/types";

const victorMono = Victor_Mono();

const cooperHewittBook = localFont({
    src: "../../public/fonts/CooperHewitt-Book.otf"
});

const cooperHewittBoldItalic = localFont({
    src: "../../public/fonts/CooperHewitt-BoldItalic.otf"
});

const cooperHewittSemibold = localFont({
    src: "../../public/fonts/CooperHewitt-Semibold.otf"
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const Home = async ({ params }: { params: Promise<{ language: Language }> }) => {
    const { language } = await params;
    const { hero } = home[language];

    return (
        <html lang={language}>
            <body className={styles.body}>
                <main>
                    <Hero content={hero} language={language} />
                </main>
            </body>
        </html>
    )
}

export default Home;